apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-frontend-deployment
  template:
    metadata:
      labels:
        app: service-frontend-deployment
    spec:
      containers:
        - name: service-frontend
          image: registry.digitalocean.com/rso-vaje/service-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: service-frontend-deployment